### ISSUE TITLE
Variant-level annotation data

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#229]
We currently don't have any variant-level annotations. I imagine these will be displayed on the variant page, and on a Trait-Locus page (lead variant + study).

Things we might want to include:
- Allele frequencies (gnomad)
- Ensembl regulatory build
- Any thing else high priority that we would like to include
- Most severe consequence across any gene https://github.com/opentargets/genetics/issues/87

Need to
- [x] Download GnomAD
- [x] Filter to include only MAF > 0.1% (in any population)
- [x] Run VEP consequences (including regulatory build)
- [x] Check output is consistent with our VEP annotations in our current index: `gs://genetics-portal-data/homo_sapiens_incl_consequences.vcf.gz`
- [x] Separate file of GRCh37 -> GRCh38 positions
- [x] Split into N chunks (required for pipeline https://github.com/opentargets/genetics/issues/167) (Ask @mkarmona how many chunks)
- [ ] Create dictionary to map Ensembl reg build cell line to cell line ontology (CLO)
- [ ] Decide how data will be displayed in the portal

Additional fields to add
- [x] CADD scores (should be possible via VEP otherwise `snipsift annotate`)
- [ ] MCAP (same as above)

Other metrics we may want to look into:
- Missense deleterious metric (MPC): https://www.biorxiv.org/content/biorxiv/early/2017/06/12/148353.full.pdf
- Missense tolerance ratio (MTR)

**Comment by edm1** [comment]
New pipeline is finished and has been run:
- Repo: https://github.com/opentargets/genetics-variant-annotation
- Output on staging: genetics-portal-staging/variant-annotation/190107/variant-annotation.parquet

Still need to map tissues to an ontology.
