### ISSUE TITLE
Therapeutic-area specific profiles for gene assignment

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#249]
This is a longer term goal. We would like to be able to have therapeutic-area specific profiles for calculating gene assignments (V2G and L2G).

This will require:
- [ ] Changing weights from source-level to tissue/feature-level in order to give us more flexibility in our customisation
- [ ] Dynamic score calculation
- [ ] Create profiles of weightings (requires speaking to experts/users about their requirements)

**Comment by edm1** [comment]
We don't have a strategy to implement this. The above is out of date. Will make a new issue when we have a strategy.
