### ISSUE TITLE
UI improvements for ESHG workshop release (polish)

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/genetics#305]
For the next major Genetics Portal release that will coincide with the ESHG workshop, there are a number of UI improvements that we can make to ensure the Portal is well-received by attendees.

List will be updated periodically:

- [ ] Improve readability and usability of navigation bar - see #295 for more information
- [ ] Ensure links and buttons are consistently styled - see #304 for more information
- [ ] Implement consistent data table design pattern - see #201 for more information
- [ ] Implement consistent page header design pattern across gene, variant, and study pages - see #303 
- [ ] Develop consistent card layout (title, question, data table, etc.) for pages with multiple card components 
- [ ] Improve search (homepage search box, navigation bar search box, autocomplete, search results page, etc.)
- [ ] Redesign home page to maintain consistent with rest of Genetics Portal branding and styles
- [ ] Fix text wrapping issue - see #300 for more information

**Comment by andrewhercules** [comment]
Ticket closed as work has been captured in other tickets
