### ISSUE TITLE
L2G API/GraphQL changes

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#412]
Design and implement GraphQL for the following queries:
- [x] Get array of top L2G genes above threshold of >=0.5 from score field `y_proba_full_model`. For study page (#411).
- [x] Provide L2G data for all genes when fixing a (study, locus). For study-locus page (#414). New table bringing all information from the L2G table. We need to add distance information from each gene to the fixed lead variant. Bring a colocalisation query into the select.
- [x] Provide L2G data for all (study, locus) when fixing a gene. Left join L2G table with the V2D (on study and lead variant) so that we have study information and association statistics. We don't need any tag variant information form the V2D table. For gene page (#413).

**Comment by mkarmona** [comment]
deployed on https://open-targets-genetics.appspot.com implementing 2 new queries and 1 query update

-  `manhattan` query
- `studyLocus2GeneTable` query
- `studiesAndLeadVariantsForGeneByL2G` query
