### ISSUE TITLE
Streamline trait mapping integration to the study table

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/genetics#488]
As a **developer** I want **to streamline the process of merging Genetics trait mappings to their respective studies** because **the current steps of this workflow are not clear enough.**

## Background

One study is related to a single trait.
At the moment trait mappings (and the therapeutic areas) are being added to the study table in 2 steps:
1. At the time the study table is generated with mappings coming from:
- GWAS Catalog (already in EFO)
- curation for UKBiobank (not complete -  needed to be updated to EFO3 - #443)
- curation for Finngen (not complete - needed and will keep needing curation as further studies are processed - #423)
2. When the `trait_efo` LUT is merged with the studies. This table is supposed to contain all the traits to EFO mappings that are present in the study table (both manual curation and automatic).

The second step adds a layer of complexity to the pipeline that we have to integrate.

## Tasks

We don't want to have obsolete curation in the generation of the study table (step 1). The present mappings will be valid, and if no EFO mapping is coming from the source, the field will be blank to be later populated by the trait_efo table.  
- [x] Drop Finngen curation from the study generation
- [x] Drop UKBiobank curation from the study generation
- [X] ~~Include up to date UKBiobank mappings to the UKBiobanks "updated" [mappings spreadsheet](https://docs.google.com/spreadsheets/d/1PotmUEirkV36dh-vpZ3GgxQg_LcOefZKbyTq0PNQ6NY/edit#gid=568383168)~~. The updated spreadsheet has been kept as it was. On top of that, the initial mappings are imported and merged with the newer ones.
- [ ] Add Finngen studies that need curation to the spreadsheet for us to be reviewed
- [x] Extract therapeutic areas from EFO OWL file.

## Acceptance tests

1. There are no GWASCat studies without a mapping.
2.  All of the UKBiobank studies are in the UKBiobank trait to EFO spreadsheet.
3.  All of the Finngen studies are in the Finngen trait to EFO spreadsheet.
4. A new Finngen study that has not been reviewed will appear in the Finngen trait to EFO spreadsheet.
