### ISSUE TITLE
Adjust page headers and cross-reference sections in all entity pages

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/genetics#518]
To promote consistency with the Genetics Portal -- and more broadly with the Platform -- I have redesigned the header components for the Genetics Portal entity pages.

The redesigned headers reuse much of the existing content already displayed and available from the GraphQL API.

**Comment by andrewhercules** [comment]
To promote consistency with the Genetics Portal -- and more broadly with the Platform -- I have redesigned the header components for the Genetics Portal entity pages.

The redesigned headers reuse much of the existing content already displayed and available from the GraphQL API.

### Gene page

![Genetics Portal Header Components - Version 2 - Design Specifications](https://user-images.githubusercontent.com/7490258/148942200-5ec9a321-4ca0-4085-a277-7c764682cff7.png)

Notes:

- [ ] Please remove the existing content and card-based style 

- [ ] For the cross-references section, please use the following link constructs:

Ensembl: `https://identifiers.org/ensembl:` + `geneInfo.id`
gnomAD: `http://gnomad.broadinstitute.org/gene/` + `geneInfo.id`
GTEx: `https://identifiers.org/gtex:` + `geneInfo.symbol`
GeneCards: `https://identifiers.org/genecards:` + `geneInfo.symbol`

- [ ] Beside the location of the gene, please display a link to the locus plot labelled "(view locus)"

- [ ] For the link to the Platform, please link to the target profile page using the following `https://platform.opentargets.org/target/` + `geneInfo.id` construct

### Variant page

- [ ] For the cross-references section, please use the link construct logic found in the existing links to Ensembl ([line 56](https://github.com/opentargets/genetics-app/blob/4d953c784965b50f7845b5595b92823c84429b2b/src/components/GnomADTable.js#L56)) and gnomAD ([line 140](https://github.com/opentargets/genetics-app/blob/4d953c784965b50f7845b5595b92823c84429b2b/src/components/GnomADTable.js#L140))

- [ ] Please remove the External References section ([lines 53-64](https://github.com/opentargets/genetics-app/blob/4d953c784965b50f7845b5595b92823c84429b2b/src/components/GnomADTable.js#L53))

### Study page

![Genetics Portal Header Components - Version 2 - Design Specifications (2)](https://user-images.githubusercontent.com/7490258/148945045-03144eee-ef2a-4fac-9cf1-9bfe1db104c6.png)
![Genetics Portal Header Components - Version 2 - Design Specifications (3)](https://user-images.githubusercontent.com/7490258/148945057-da13c96f-c925-4cb4-9e3e-88716c4df773.png)
![Genetics Portal Header Components - Version 2 - Design Specifications (4)](https://user-images.githubusercontent.com/7490258/148945075-5b98a1b0-3d03-4361-8a16-be665abde9
![Genetics Portal Header Components - Version 2 - Design Specifications (5)](https://user-images.githubusercontent.com/7490258/148945100-b90cf897-7a44-408a-b37f-581923ce8603.png)
c6.png)

- [ ] Please create a new section called "Study summary" that lists the Author (`studyInfo.pubAuthor`), Year (`studyInfo.pubDate` formatted to only show the year), Publication (`studyInfo.pubJournal`), and PubMed (`studyInfo.pmid` with a link to EuropePMC using the `http://europepmc.org/article/MED/` + `studyInfo.pmid link construct). If these fields are not available, please display "N/A"

- For the "Has summary stats" field in the "Study summary" section, display "Yes" if `studyInfo.hasSumstats` == `true`, otherwise display "No"

- [ ] The "Study size" section can stay as-is

- [ ] For the cross-references section, please reuse the logic already used in the [StudySummary.js section](https://github.com/opentargets/genetics-app/blob/main/src/components/StudySummary.js) as it accounts for studies from GWAS Catalog, UK Biobank (NEALE and SAIGE), and FinnGen. However, with the SAIGE link, instead of showing "Homepage", please display the `studyInfo.studyId` field, formatted to remove the `SAIGE_` prefix

Example GraphQL queries:

- SAIGE: [740_1](https://api.genetics.opentargets.org/graphql/browser?query=query%20study%20%7B%0A%20%20studyInfo(studyId%3A%22SAIGE_740_1%22)%7B%0A%20%20%20%20studyId%0A%20%20%20%20traitReported%0A%20%20%20%20source%0A%20%20%20%20traitEfos%0A%20%20%20%20pmid%0A%20%20%20%20pubDate%0A%20%20%20%20pubJournal%0A%20%20%20%20pubTitle%0A%20%20%20%20pubAuthor%0A%20%20%20%20hasSumstats%0A%20%20%20%20numAssocLoci%0A%20%20%7D%0A%7D&operationName=study)
- GWAS Catalog: [GCST90012110](https://api.genetics.opentargets.org/graphql/browser?query=query%20study%20%7B%0A%20%20studyInfo(studyId%3A%22GCST90012110%22)%7B%0A%20%20%20%20studyId%0A%20%20%20%20traitReported%0A%20%20%20%20source%0A%20%20%20%20traitEfos%0A%20%20%20%20pmid%0A%20%20%20%20pubDate%0A%20%20%20%20pubJournal%0A%20%20%20%20pubTitle%0A%20%20%20%20pubAuthor%0A%20%20%20%20hasSumstats%0A%20%20%20%20numAssocLoci%0A%20%20%7D%0A%7D&operationName=study)
- FinnGen: [RX_STATIN](https://api.genetics.opentargets.org/graphql/browser?query=query%20study%20%7B%0A%20%20studyInfo(studyId%3A%22FINNGEN_R5_RX_STATIN%22)%7B%0A%20%20%20%20studyId%0A%20%20%20%20traitReported%0A%20%20%20%20source%0A%20%20%20%20traitEfos%0A%20%20%20%20pmid%0A%20%20%20%20pubDate%0A%20%20%20%20pubJournal%0A%20%20%20%20pubTitle%0A%20%20%20%20pubAuthor%0A%20%20%20%20hasSumstats%0A%20%20%20%20numAssocLoci%0A%20%20%7D%0A%7D&operationName=study)
- UK Biobank: [23108](https://api.genetics.opentargets.org/graphql/browser?query=query%20study%20%7B%0A%20%20studyInfo(studyId%3A%22NEALE2_23108_raw%22)%7B%0A%20%20%20%20studyId%0A%20%20%20%20traitReported%0A%20%20%20%20source%0A%20%20%20%20traitEfos%0A%20%20%20%20pmid%0A%20%20%20%20pubDate%0A%20%20%20%20pubJournal%0A%20%20%20%20pubTitle%0A%20%20%20%20pubAuthor%0A%20%20%20%20hasSumstats%0A%20%20%20%20numAssocLoci%0A%20%20%7D%0A%7D&operationName=study)

**Comment by andrewhercules** [comment]
### Variant page

![Genetics Portal Header Components - Version 2 - Design Specifications (1)](https://user-images.githubusercontent.com/7490258/148947023-6a50e74a-125f-4229-863b-53d2384a36ac.png)

- [ ] Use the [FontAwesome map-pin icon](url) in Open Targets blue `#3489ca`

- [ ] For the cross-references section, please use the link construct logic found in the existing links to Ensembl ([line 56](https://github.com/opentargets/genetics-app/blob/4d953c784965b50f7845b5595b92823c84429b2b/src/components/GnomADTable.js#L56)) and gnomAD ([line 140](https://github.com/opentargets/genetics-app/blob/4d953c784965b50f7845b5595b92823c84429b2b/src/components/GnomADTable.js#L140))

- [ ] Please remove the External References section ([lines 53-64](https://github.com/opentargets/genetics-app/blob/4d953c784965b50f7845b5595b92823c84429b2b/src/components/GnomADTable.js#L53))

**Comment by andrewhercules** [comment]
### Study page

![Genetics Portal Header Components - Version 2 - Design Specifications (2)](https://user-images.githubusercontent.com/7490258/148945045-03144eee-ef2a-4fac-9cf1-9bfe1db104c6.png)

![Genetics Portal Header Components - Version 2 - Design Specifications (3)](https://user-images.githubusercontent.com/7490258/148945057-da13c96f-c925-4cb4-9e3e-88716c4df773.png)

![Genetics Portal Header Components - Version 2 - Design Specifications (4)](https://user-images.githubusercontent.com/7490258/148945075-5b98a1b0-3d03-4361-8a16-be665abde9c6.png)

![Genetics Portal Header Components - Version 2 - Design Specifications (5)](https://user-images.githubusercontent.com/7490258/148945100-b90cf897-7a44-408a-b37f-581923ce8603.png)

- [ ] Use the [FontAwesome chart-bar icon](https://fontawesome.com/v5.15/icons/chart-bar?style=solid) in Open Targets blue `#3489ca`

- [ ] Please create a new section called "Study summary" that lists the Author (`studyInfo.pubAuthor`), Year (`studyInfo.pubDate` formatted to only show the year), Publication (`studyInfo.pubJournal`), and PubMed (`studyInfo.pmid` with a link to EuropePMC using the `http://europepmc.org/article/MED/` + `studyInfo.pmid link construct). If these fields are not available, please display "N/A"

- For the "Has summary stats" field in the "Study summary" section, display "Yes" if `studyInfo.hasSumstats` == `true`, otherwise display "No"

- [ ] The "Study size" section can stay as-is

- [ ] For the cross-references section, please reuse the logic already used in the [StudySummary.js section](https://github.com/opentargets/genetics-app/blob/main/src/components/StudySummary.js) as it accounts for studies from GWAS Catalog, UK Biobank (NEALE and SAIGE), and FinnGen and shows the correct cross-reference link depending on the `studyInfo.studyId` field. With the SAIGE link, instead of showing "Homepage", please display the `studyInfo.studyId` field, formatted to remove the `SAIGE_` prefix

Below are sample GraphQL queries for each different study source:

- SAIGE: [740_1](https://api.genetics.opentargets.org/graphql/browser?query=query%20study%20%7B%0A%20%20studyInfo(studyId%3A%22SAIGE_740_1%22)%7B%0A%20%20%20%20studyId%0A%20%20%20%20traitReported%0A%20%20%20%20source%0A%20%20%20%20traitEfos%0A%20%20%20%20pmid%0A%20%20%20%20pubDate%0A%20%20%20%20pubJournal%0A%20%20%20%20pubTitle%0A%20%20%20%20pubAuthor%0A%20%20%20%20hasSumstats%0A%20%20%20%20numAssocLoci%0A%20%20%7D%0A%7D&operationName=study)
- GWAS Catalog: [GCST90012110](https://api.genetics.opentargets.org/graphql/browser?query=query%20study%20%7B%0A%20%20studyInfo(studyId%3A%22GCST90012110%22)%7B%0A%20%20%20%20studyId%0A%20%20%20%20traitReported%0A%20%20%20%20source%0A%20%20%20%20traitEfos%0A%20%20%20%20pmid%0A%20%20%20%20pubDate%0A%20%20%20%20pubJournal%0A%20%20%20%20pubTitle%0A%20%20%20%20pubAuthor%0A%20%20%20%20hasSumstats%0A%20%20%20%20numAssocLoci%0A%20%20%7D%0A%7D&operationName=study)
- FinnGen: [RX_STATIN](https://api.genetics.opentargets.org/graphql/browser?query=query%20study%20%7B%0A%20%20studyInfo(studyId%3A%22FINNGEN_R5_RX_STATIN%22)%7B%0A%20%20%20%20studyId%0A%20%20%20%20traitReported%0A%20%20%20%20source%0A%20%20%20%20traitEfos%0A%20%20%20%20pmid%0A%20%20%20%20pubDate%0A%20%20%20%20pubJournal%0A%20%20%20%20pubTitle%0A%20%20%20%20pubAuthor%0A%20%20%20%20hasSumstats%0A%20%20%20%20numAssocLoci%0A%20%20%7D%0A%7D&operationName=study)
- UK Biobank: [23108](https://api.genetics.opentargets.org/graphql/browser?query=query%20study%20%7B%0A%20%20studyInfo(studyId%3A%22NEALE2_23108_raw%22)%7B%0A%20%20%20%20studyId%0A%20%20%20%20traitReported%0A%20%20%20%20source%0A%20%20%20%20traitEfos%0A%20%20%20%20pmid%0A%20%20%20%20pubDate%0A%20%20%20%20pubJournal%0A%20%20%20%20pubTitle%0A%20%20%20%20pubAuthor%0A%20%20%20%20hasSumstats%0A%20%20%20%20numAssocLoci%0A%20%20%7D%0A%7D&operationName=study)

**Comment by andrewhercules** [comment]
### Study-locus page

![Genetics Portal Header Components - Version 2 - Design Specifications (7)](https://user-images.githubusercontent.com/7490258/150138117-d07de588-7f42-4909-8ef8-6bce19735b6f.png)

- [ ] Use the [FontAwesome project-diagram icon](https://fontawesome.com/v5.15/icons/project-diagram?style=solid) in Open Targets blue `#3489ca`

- [ ] In the cross-references section, add two entries: 

1. "Study ID:" that shows the `studyInfo.studyId` value and links to the study page (`https://genetics.opentargets.org/study/` + `studyInfo.studyId`)
2. "Variant ID:" that shows the `variantInfo.chromosome` + `_` + `variantInfo.position` + `_` + `variantInfo.refAllele` + `_` and `variantInfo.altAllele` (e.g. 2_21041028_G_A) and links to the variant page (`https://genetics.opentargets.org/variant/` +`variantInfo.chromosome` + `_` + `variantInfo.position` + `_` + `variantInfo.refAllele` + `_` and `variantInfo.altAllele`) 

- [ ] Reuse the existing "Association summary" section and content, but add a new "Study-variant associations" label to the existing p-value, beta, and beta 95% confidence interval entries

- [ ] In a new section called "Study details", use the `studyInfo` endpoint to display Author (`studyInfo.pubAuthor`), Year (`studyInfo.pubDate` formatted to show the year only), and Publication (`studyInfo.pubJournal`)

- [ ] In a new section called "Variant details", using the `variantInfo` endpoint to display GRCh38 (`variantInfo.chromosome`:`variantInfo.position`), GRCh37 (`variantInfo.chromosomeB37`:`variantInfo.positionB37`), and RSID (`variantInfo.rsId`)

- If the `variantInfo.rsId` is `null` or blank, display `N/A`

**Comment by d0choa** [comment]
Minor things to take into account:
- I like the title in the study-locus page but we should be prepared to have some pressure in the UI in very long trait names, as opposed to the current implementation that contains the variant in a second row. 
- Remember the "Association summary" in the study-locus page has some fields that depend on whether it's a quantitative trait (beta) or not (odds ratio). This is an [alternative example](https://genetics.opentargets.org/study-locus/GCST004132/16_50724938_G_A)

**Comment by ktsirigos** [comment]
work completed
